//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorthIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int Id { get; set; }
        public int CreditCardExpirationMonth { get; set; }
        public int CreditCardExpirationYear { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardName { get; set; }
        public int CreditCardVerificationValue { get; set; }
        public string Email { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingState { get; set; }
        public int ZipCode { get; set; }
    }
}
